"""create users table

Revision ID: e1080895fa59
Revises: bf6852a64430
Create Date: 2023-02-21 16:34:50.118208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1080895fa59'
down_revision = 'bf6852a64430'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['verification_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'verification_code')
    # ### end Alembic commands ###
